// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt1he5zggvV_IbraEynqbqezVlBY_63Bw',
    appId: '1:1002757282160:web:4a988e44ed647f590157b5',
    messagingSenderId: '1002757282160',
    projectId: 'taxi-n-ride-6d9a8',
    authDomain: 'taxi-n-ride-6d9a8.firebaseapp.com',
    storageBucket: 'taxi-n-ride-6d9a8.firebasestorage.app',
    measurementId: 'G-SB5GY5KNE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM52ye_fI1v3wirNoyI8DZZgNlOexoA_w',
    appId: '1:1002757282160:android:e5604f55c55d05e90157b5',
    messagingSenderId: '1002757282160',
    projectId: 'taxi-n-ride-6d9a8',
    storageBucket: 'taxi-n-ride-6d9a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA351BWhVj1UMY8fSDuYJwru4IzoAj4gts',
    appId: '1:1002757282160:ios:0e2d14da9e658fa10157b5',
    messagingSenderId: '1002757282160',
    projectId: 'taxi-n-ride-6d9a8',
    storageBucket: 'taxi-n-ride-6d9a8.firebasestorage.app',
    iosBundleId: 'com.example.taxiNRide',
  );
}
